background_b: 255
background_g: 86
background_r: 150
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_localhost__37047: 'http://localhost:37047/'}
rosversion: '1.12.13

  '
run_id: a5518342-7813-11e8-a48c-28565aa3b05b
